#ifndef __CMT2300A_PARAMS_H
#define __CMT2300A_PARAMS_H

#if defined (CMT2300)
/************************************************************
;---------------------------------------
;  CMT2219B Configuration File
;  Generated by CMOSTEK RFPDK 1.50
;  2020.02.26 09:24
;---------------------------------------
; Mode                    = Advanced
; Part Number             = CMT2219B
; Frequency               = 433.920 MHz
; Xtal Frequency          = 26.0000 MHz
; Demodulation            = FSK
; AGC                     = On
; Data Rate               = 10.0 kbps
; Deviation               = 10.0 kHz
; Rx Xtal Tol.            = 40 ppm
; Bandwidth               = Auto-Select kHz
; CDR Type                = Counting
; CDR DR Range            = NA
; AFC                     = On
; AFC Method              = Auto-Select
; Data Representation     = 0:F-low 1:F-high
; Rx Duty-Cycle           = Off
; Sleep Timer             = Off
; Sleep Time              = NA
; Rx Timer                = Off
; Rx Time T1              = NA
; Rx Time T2              = NA
; Rx Exit State           = SLEEP
; SLP Mode                = Disable
; RSSI Valid Source       = PJD
; PJD Window              = 8 Jumps
; LFOSC Calibration       = On
; Xtal Stable Time        = 2480 us
; RSSI Compare TH         = NA
; Data Mode               = Packet
; Whitening               = Disable
; Whiten Type             = NA
; Whiten Seed Type        = NA
; Whiten Seed             = NA
; Manchester              = Disable
; Manchester Type         = NA
; FEC                     = Disable
; FEC Type                = NA
; Packet Type             = Variable Length
; Node-Length Position    = First Node, then Length
; Payload Bit Order       = Start from msb
; Preamble Rx Size        = 2
; Preamble Value          = 170
; Preamble Unit           = 8-bit
; Sync Size               = 2-byte
; Sync Value              = 34952
; Sync Tolerance          = None
; Sync Manchester         = Disable
; Node ID Size            = NA
; Node ID Value           = NA
; Node ID Mode            = None
; Node ID Err Mask        = Disable
; Node ID Free            = Disable
; Payload Length          = 32
; CRC Options             = CCITT-16
; CRC Seed                = 0 crc_seed
; CRC Range               = Entire Payload
; CRC Swap                = Start from MSB
; CRC Bit Invert          = Normal
; CRC Bit Order           = Start from bit 15
; Dout Mute               = Off
; Dout Adjust Mode        = Disable
; Dout Adjust Percentage  = NA
; Collision Detect        = Off
; Collision Detect Offset = NA
; RSSI Detect Mode        = Always
; RSSI Filter Setting     = No Filtering
; RF Performance          = High
; LBD Threshold           = 2.4 V
; RSSI Offset             = 26
; RSSI Offset Sign        = 1

************************************************************/
/* [CMT Bank] */
 u8 g_cmt2300aCmtBank[CMT2300A_CMT_BANK_SIZE] = {
	0x00,
	0x66,
	0xEC,
	0x1C,
	0x30,
	0x80,
	0x14,
	0x08,
	0x11,
	0x02,
	0x02,
	0x00
};

/* [System Bank] */
 u8 g_cmt2300aSystemBank[CMT2300A_SYSTEM_BANK_SIZE] = {
/*0x0C*/  0xAE,
/*0x0D*/  0xE0,
/*0x0E*/  0x35,
/*0x0F*/  0x00,
/*0x10*/  0x00,
/*0x11*/  0xF4,
/*0x12*/  0x10,
/*0x13*/  0xE2,
/*0x14*/  0x42,
/*0x15*/  0x20,
/*0x16*/  0x00,
/*0x17*/  0x81,	
};

/* [Frequency Bank] */
 u8 g_cmt2300aFrequencyBank[CMT2300A_FREQUENCY_BANK_SIZE] = {
	0x46,
	0xBC,
	0x6C,
	0x8B,
	0x46,
	0xB1,
	0x13,
	0x1B
};

/* [Data Rate Bank] */
 u8 g_cmt2300aDataRateBank[CMT2300A_DATA_RATE_BANK_SIZE] = {
  0x3F,
  0xF0,
  0x73,
  0x10,
  0x63,
  0x12,
  0x0E,
  0x0B,
  0x9F,
  0x6C,
  0x29,
  0x29,
  0xC0,
  0x04,
  0x01,
  0x53,
  0x20,
  0x00,
  0xB4,
  0x00,
  0x00,
  0x01,
  0x00,
  0x00
};

/* [Baseband Bank] */
 u8 g_cmt2300aBasebandBank[CMT2300A_BASEBAND_BANK_SIZE] = {
  0x0A,
  0x08,
  0x00,
  0xAA,
  0x26,
  0x00,
  0x00,
  0x00,
  0x00,
  0x91,
  0xD3,
  0x91,
  0xD3,
  0x05,
  0x1F,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x03,
  0xFF,
  0xFF,
  0x6C,
  0xFF,
  0x00,
  0x00,
  0x1F,
  0x10
};

/* [Tx Bank] */
 u8 g_cmt2300aTxBank[CMT2300A_TX_BANK_SIZE] = {
  0x70,
  0xFF,
  0x0E,
  0x00,
  0x00,
  0x30,
  0x00,
  0x42,
  0x0C,
  0x7F,
  0x7F
};
#endif
#endif
